# 
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"

# 
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate"